//! The per-DM relay key (spec §4.5, D17): generated by the sequencer, sent
//! over a direct link encrypted under the MLS exporter secret at one epoch.
use aes_gcm::aead::{Aead, KeyInit, Payload};
use aes_gcm::{Aes256Gcm, Nonce};
use async_trait::async_trait;
use hkdf::Hkdf;
use sha2::Sha256;
use xmtp_mls::context::XmtpSharedContext;

use crate::MeshError;

pub(crate) const EXPORTER_LABEL: &str = "xmtp-mesh relay v1";
const WRAP_INFO: &[u8] = b"xmtp-mesh relay key v1";

/// Reads a group's current MLS epoch and exporter secret from the local
/// client (the node is not the MLS client).
#[async_trait]
pub trait RelayExporter: Send + Sync {
    /// `(epoch, secret)` with label `"xmtp-mesh relay v1"`, empty context,
    /// 32 bytes; `None` when the client does not know the group.
    async fn exporter_secret(&self, group_id: &[u8]) -> Result<Option<(u64, [u8; 32])>, MeshError>;
}

/// The production [`RelayExporter`]: loads the OpenMLS group from the
/// client's storage (read-only, no group lock, like `groups/oneshot.rs`).
pub struct ClientRelayExporter<C>(pub xmtp_mls::Client<C>);

#[async_trait]
impl<C> RelayExporter for ClientRelayExporter<C>
where
    C: XmtpSharedContext + Send + Sync + 'static,
{
    async fn exporter_secret(&self, group_id: &[u8]) -> Result<Option<(u64, [u8; 32])>, MeshError> {
        use openmls::group::{GroupId, MlsGroup};
        use openmls::prelude::OpenMlsProvider;
        let provider = self.0.context.mls_provider();
        let group = MlsGroup::load(provider.storage(), &GroupId::from_slice(group_id))
            .map_err(|e| MeshError::Relay(e.to_string()))?;
        let Some(group) = group else {
            return Ok(None);
        };
        let secret = group
            .export_secret(provider.crypto(), EXPORTER_LABEL, &[], 32)
            .map_err(|e| MeshError::Relay(e.to_string()))?;
        let secret: [u8; 32] = secret
            .try_into()
            .map_err(|_| MeshError::Relay("exporter secret is not 32 bytes".into()))?;
        Ok(Some((group.epoch().as_u64(), secret)))
    }
}

fn wrap_cipher(exporter: &[u8; 32]) -> Aes256Gcm {
    let mut key = [0u8; 32];
    Hkdf::<Sha256>::new(None, exporter)
        .expand(WRAP_INFO, &mut key)
        .expect("32 bytes is a valid HKDF length");
    Aes256Gcm::new_from_slice(&key).expect("32-byte key")
}

fn aad(group_id: &[u8], epoch: u64) -> Vec<u8> {
    let mut a = group_id.to_vec();
    a.extend_from_slice(&epoch.to_be_bytes());
    a
}

/// Returns `(nonce, ciphertext)`.
pub(crate) fn wrap_key(
    exporter: &[u8; 32],
    group_id: &[u8],
    epoch: u64,
    relay_key: &[u8; 32],
) -> ([u8; 12], Vec<u8>) {
    let nonce: [u8; 12] = rand::random();
    let ct = wrap_cipher(exporter)
        .encrypt(
            Nonce::from_slice(&nonce),
            Payload {
                msg: relay_key,
                aad: &aad(group_id, epoch),
            },
        )
        .expect("AES-GCM encryption of 32 bytes cannot fail");
    (nonce, ct)
}

pub(crate) fn unwrap_key(
    exporter: &[u8; 32],
    group_id: &[u8],
    epoch: u64,
    nonce: &[u8],
    ciphertext: &[u8],
) -> Result<[u8; 32], MeshError> {
    if nonce.len() != 12 {
        return Err(MeshError::Relay("bad offer nonce".into()));
    }
    let key = wrap_cipher(exporter)
        .decrypt(
            Nonce::from_slice(nonce),
            Payload {
                msg: ciphertext,
                aad: &aad(group_id, epoch),
            },
        )
        .map_err(|_| MeshError::Relay("relay key offer does not open".into()))?;
    key.try_into()
        .map_err(|_| MeshError::Relay("relay key is not 32 bytes".into()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wrap_unwrap_binds_group_and_epoch() {
        let (nonce, ct) = wrap_key(&[1; 32], b"g", 3, &[9; 32]);
        assert_eq!(unwrap_key(&[1; 32], b"g", 3, &nonce, &ct).unwrap(), [9; 32]);
        assert!(unwrap_key(&[1; 32], b"g", 4, &nonce, &ct).is_err());
        assert!(unwrap_key(&[1; 32], b"h", 3, &nonce, &ct).is_err());
        assert!(unwrap_key(&[2; 32], b"g", 3, &nonce, &ct).is_err());
    }
}
